name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Frontend Tests

    steps:
      - name: Fetch code
        uses: actions/checkout@v4.2.2

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Project Dependencies
        run: npm install

      - name: Run the Frontend Tests
        run: npm run test:ci

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    name: Production Build

    needs:
      - test

    steps:
      - name: Fetch code
        uses: actions/checkout@v4.2.2

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Project Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: production_dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    name: Deploy

    needs:
      - build

    steps:
      - name: Trigger Render
        run: curl -X GET ${{ secrets.RENDER_HOOK }}
